# Black formatting
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

# iSort
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
virtual_env = "venv"

[tool.flake8]
max-line-length = 88
ignore = ["E501", "W503", "E203", "E226"]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "env",
]
# E501: Line too long
# W503: Line break occurred before binary operator
# E226: Missing white space around arithmetic operator


[tool.pyupgrade]
py39plus = true

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
markers = [
    "training: tests that involve training",
]

# Pytest cov
[tool.coverage.run]
omit=["src/evaluate.py", "src/serve.py"]
